/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class ClouderTest {
    @Test
    public void testAppHasAGreeting() {
        Clouder classUnderTest = new Clouder();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
